name: Test docker symlinks
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: mkdir deploy
      - run: ln -s ../README.md readme
        working-directory: ./deploy
      - run: docker build -t test .
      - run: docker run test ls -la /deploy
      - run: docker run test cat /deploy/readme