name: Test docker symlinks
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls -la
      - run: mkdir deploy
      - run: ln -s ../README.md readme
        working-directory: ./deploy
      - run: ls -la deploy
      - run: ls -la .
      - run: docker build -t test .
      - run: docker run test ls -la /deploy